const CONFIG = {
    introTitle: 'Chào thằng lòn Đức Anh',
    introDesc: `Tao là Cường đây`,
    btnIntro: 'Ấn vào đây',
    title: 'Bây giờ m có 2 lựa chọn ',
    desc: 'Nghĩ kĩ nhé ',
    btnYes: 'Cho tao 2 đôi giầy',
    btnNo: 'Được tao bao đi ăn lẩu ',
    question:'Chúc mừng m đã quay vào ô may mắn :))) ',
    btnReply: 'M lừa tao',
    reply: 'Đúng rồi đó ',
    mess: 'Chuýt sì',
    messDesc: 'Lêu lêu',
    btnAccept: 'Chào thằng lòn nha :>> ',
}
