const CONFIG = {
    introTitle: 'Chào chị Trúc',
    introDesc: `Em là Cường`,
    btnIntro: 'hihi',
    title: 'Bây giờ chị có 2 lựa chọn ',
    desc: 'Nghĩ kĩ nhé ',
    btnYes: 'Cho em 100tr',
    btnNo: 'Được tao bao đi ăn lẩu ',
    question:'Chúc mừng chị đã quay vào ô may mắn :))) ',
    btnReply: 'M lừa tao',
    reply: 'Đúng rồi đó ',
    mess: 'Chuýt sì',
    messDesc: 'Lêu lêu',
    btnAccept: 'Chào chị nha :>> ',
}
