const CONFIG = {
    introTitle: 'Chào Trần Linh',
    introDesc: `Tao là Cường`,
    btnIntro: 'hihi',
    title: 'Bây giờ m có 2 lựa chọn ',
    desc: 'Nghĩ kĩ nhé ',
    btnYes: 'Cho tao 100tr',
    btnNo: 'Được tao bao Tok',
    question:'Chúc mừng m đã quay vào ô may mắn :))) ',
    btnReply: 'Xin cám ơn',
    reply: 'Hehehe :> ',
    mess: 'Chuýt sì',
    messDesc: 'Hãy nhìn đây',
    btnAccept: 'Chào',
}
